# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dctl < Formula
  desc "Simple utility to collect snippets."
  homepage "https://github.com/mchmarny/snip"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mchmarny/snip/releases/download/v0.5.0/dctl_darwin_arm64"
      sha256 "0225874f307887dc8f654cee506dc977300a5e57235f1010c25b3bd21b5741eb"

      def install
        bin.install "dctl_darwin_arm64" => "dctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mchmarny/snip/releases/download/v0.5.0/dctl_darwin_amd64"
      sha256 "561ab5bcd22adfc79839436dc94b8f1b4a29a2faaa4b5bce1da32ce39a83c578"

      def install
        bin.install "dctl_darwin_amd64" => "dctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mchmarny/snip/releases/download/v0.5.0/dctl_linux_arm64"
      sha256 "cbd5d4ff1c3fb15ff2fcda998077dee634491eb19a319535d9204c2fb846ad3d"

      def install
        bin.install "dctl_linux_arm64" => "dctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mchmarny/snip/releases/download/v0.5.0/dctl_linux_amd64"
      sha256 "7d9572355b86d791ace6369ed00ca5bc6ac61d16c5d5cd331036c77e33693d8d"

      def install
        bin.install "dctl_linux_amd64" => "dctl"
      end
    end
  end
end
