# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snip < Formula
  desc "Simple utility to collect snippets."
  homepage "https://github.com/mchmarny/snip"
  version "0.5.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mchmarny/snip/releases/download/v0.5.1/snip_darwin_arm64"
      sha256 "1fcabfb36740978f060aec33bd9b6f99bcdf096314a00fa02688979bdb9e7a0e"

      def install
        bin.install "snip_darwin_arm64" => "snip"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mchmarny/snip/releases/download/v0.5.1/snip_darwin_amd64"
      sha256 "15167b830d0da8f75e8ce7edeb27de1ef7822f2bd3108330055d637eeef11bbc"

      def install
        bin.install "snip_darwin_amd64" => "snip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mchmarny/snip/releases/download/v0.5.1/snip_linux_arm64"
      sha256 "e2a2442370b5196218bbfce1ac0b53cd66fba0dd224e34567786935f6fa3d331"

      def install
        bin.install "snip_linux_arm64" => "snip"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mchmarny/snip/releases/download/v0.5.1/snip_linux_amd64"
      sha256 "5723063dbf16f549a431089eb8e644b08d5085bd60b340390a3d02531a9a19dd"

      def install
        bin.install "snip_linux_amd64" => "snip"
      end
    end
  end
end
